image: node:latest

# Cache modules in between jobs
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - build
  - deploy

npm-install:
  stage: .pre
  script:
    - npm install

build-job:
  stage: build
  script:
    - npm run rollup

deploy:
  stage: deploy
  only:
    - develop
    - /^devops\/.*$/
  script:
    - echo "@eslovensko:registry=https://gitlab.slovenskoit.sk/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">.npmrc
    - echo "//gitlab.slovenskoit.sk/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - npm run deploy
